version: '3'
services:
  web:
    image: nginx
    container_name: "nginx_contacts"
    ports:
      - "80:80"

  db:
    image: postgres
    container_name: "psql_contacts"
    restart: always
    environment: 
      POSTGRES_PASSWORD: bela1010
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wagner.rose@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bela1010"
    ports:
      - "15432:80"
    depends_on:
      - db

  app:
    image: contacts_container
    container_name: "app_contacts"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - db
