default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: bela1010
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contatos_development

test:
  <<: *default
  database: contatos_test

production:
  <<: *default
  database: contatos_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
